// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_tYaFycm9HOuvBth54kOG9NmoJnD6Lk',
    appId: '1:29401793255:web:9e95788a83ad3aa9d99842',
    messagingSenderId: '29401793255',
    projectId: 'quizu-6b81f',
    authDomain: 'quizu-6b81f.firebaseapp.com',
    storageBucket: 'quizu-6b81f.appspot.com',
    measurementId: 'G-MSCFWY2ENX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IAPq95iNwGQz6HuUzASw2LQB3_osfas',
    appId: '1:29401793255:android:f05b80a859ba8ce4d99842',
    messagingSenderId: '29401793255',
    projectId: 'quizu-6b81f',
    storageBucket: 'quizu-6b81f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcNaKamz8e2L2B2p5w4Ff-5_djScco57s',
    appId: '1:29401793255:ios:590b9a8829e118cfd99842',
    messagingSenderId: '29401793255',
    projectId: 'quizu-6b81f',
    storageBucket: 'quizu-6b81f.appspot.com',
    iosClientId: '29401793255-v3pnghnpeh1mueur54nss6m59u1bhstl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcNaKamz8e2L2B2p5w4Ff-5_djScco57s',
    appId: '1:29401793255:ios:590b9a8829e118cfd99842',
    messagingSenderId: '29401793255',
    projectId: 'quizu-6b81f',
    storageBucket: 'quizu-6b81f.appspot.com',
    iosClientId: '29401793255-v3pnghnpeh1mueur54nss6m59u1bhstl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
